if ! has sway; then
    echo "  Skipping (sway not found)"
    return
fi

echo "Linking sway config..."
link "$DOTFILES/sway/config" "$HOME/.config/sway/config"

mkdir -p "$HOME/.config/sway/local"

if [ "$MOD_CHOICE" = "2" ]; then
    echo "set \$mod Mod4" > "$HOME/.config/sway/local/mod.g"
else
    echo "set \$mod Mod1" > "$HOME/.config/sway/local/mod.g"
fi

echo "set \$term $TERMINAL" > "$HOME/.config/sway/local/terminal.g"
echo "  Generated ~/.config/sway/local/terminal.g"

if ! [ -f "$HOME/.config/sway/local/outputs" ]; then
    {
        echo "# Machine-specific output configuration"
        echo "# normal: output eDP-1 resolution 1920x1080@60Hz position 0,0"
        echo "# force custom res: output Virtual-1 resolution --custom 3440x1440@60Hz position 0,0 scale 1.25"
    } > "$HOME/.config/sway/local/outputs"
    echo "  Created ~/.config/sway/local/outputs"
fi

WALL=$(cat "$HOME/.config/wallpaper" 2>/dev/null)
if [ -n "$WALL" ] && [ -f "$WALL" ]; then
    echo "output * bg \"$WALL\" fill" > "$HOME/.config/sway/local/wallpaper"
else
    echo "# output * bg \"\$HOME/Pictures/wallpapers/...\" fill" > "$HOME/.config/sway/local/wallpaper"
fi
echo "  Generated ~/.config/sway/local/wallpaper"

{
    echo "# Auto-generated by bootstrap — reflects currently installed packages"
    echo "# Do not edit manually; use local/custom instead"
    echo ""

    if has waybar; then
        echo "exec waybar"
    fi

    if has swaybg && [ -x "$HOME/.local/libexec/set-wallpaper" ]; then
        echo "bindsym \$mod+Ctrl+w exec sh -c 'cm-image -m cover | ~/.local/libexec/set-wallpaper'"
    fi

    if has pactl; then
        echo "bindsym --locked XF86AudioMute exec pactl set-sink-mute @DEFAULT_SINK@ toggle"
        echo "bindsym --locked XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -5%"
        echo "bindsym --locked XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +5%"
        echo "bindsym --locked XF86AudioMicMute exec pactl set-source-mute @DEFAULT_SOURCE@ toggle"
    fi

    if has cm-volmixer; then
        echo "bindsym \$mod+BackSpace exec ~/.local/bin/cm-volmixer"
    fi

    if has cm-alias; then
        echo "bindsym \$mod+a exec ~/.local/bin/cm-alias"
    fi

    if has swayidle && has powerctl; then
        echo "exec swayidle -w \\"
        echo "    timeout 300 'powerctl lock' \\"
        echo "    timeout 600 'swaymsg \"output * dpms off\"' resume 'swaymsg \"output * dpms on\"' \\"
        echo "    before-sleep 'powerctl lock'"
    fi
} > "$HOME/.config/sway/local/utilities.g"
echo "  Generated ~/.config/sway/local/utilities.g"

if ! [ -f "$HOME/.config/sway/local/custom" ]; then
    {
        echo "# Machine-specific custom keybinds -- add your own below"
        echo "# e.g. bindsym --locked XF86MonBrightnessUp exec brightnessctl set +10%"
        echo ""
        echo "seat seat0 xcursor_theme Graphite-dark-mocha 24"
    } > "$HOME/.config/sway/local/custom"
    echo "  Created ~/.config/sway/local/custom"
fi
