if has sway; then
    echo "Linking sway config..."
    link "$DOTFILES/sway/config" "$HOME/.config/sway/config"

    echo ""
    echo "  Add to ~/.profile to auto-launch on TTY1:"
    echo '    if [ -z "$WAYLAND_DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then'
    echo '      exec sway'
    echo '    fi'
    echo ""
    echo "  On Void Linux, launch via:"
    echo "    dbus-run-session sway"
    echo ""

    mkdir -p "$HOME/.config/sway/local"

    if [ "$MOD_CHOICE" = "2" ]; then
        echo "set \$mod Mod4" > "$HOME/.config/sway/local/mod.g"
    else
        echo "set \$mod Mod1" > "$HOME/.config/sway/local/mod.g"
    fi

    if [ -f "$DOTFILES/local/bin/cm-swirl" ]; then
        echo "Linking cm-swirl..."
        link "$DOTFILES/local/bin/cm-swirl" "$HOME/.local/bin/cm-swirl"
    fi

    if ! [ -f "$HOME/.config/sway/local/outputs.g" ]; then
        cat > "$HOME/.config/sway/local/outputs.g" <<'EOF'
# Machine-specific output configuration
# Find output names: swaymsg -t get_outputs
#
# Example: output Virtual-1 resolution --custom 3440x1440@60Hz position 0,0 scale 1.25
EOF
        echo "  Created ~/.config/sway/local/outputs.g"
    fi

    {
        echo "# Auto-generated by bootstrap — reflects currently installed packages"
        echo "# Do not edit manually; use local/custom.g instead"
        echo ""

        if has waybar; then
            echo "exec waybar"
            echo 'bindsym $mod+Shift+w exec sh -c "pkill waybar || waybar"'
        fi

        if has swayidle && has powerctl; then
            echo "exec swayidle -w \\"
            echo "    timeout 300 'powerctl lock &' \\"
            echo "    timeout 600 'swaymsg \"output * dpms off\"' resume 'swaymsg \"output * dpms on\"' \\"
            echo "    before-sleep 'powerctl lock'"
        fi

        echo ""

        if [ "$TERMINAL" ]; then
            echo "bindsym \$mod+Return exec $TERMINAL"
        fi

        if has cm-launcher; then
            echo 'bindsym $mod+d exec cm-launcher'
        fi

        if has pactl; then
            echo 'bindsym --locked XF86AudioMute        exec pactl set-sink-mute @DEFAULT_SINK@ toggle'
            echo 'bindsym --locked XF86AudioLowerVolume  exec pactl set-sink-volume @DEFAULT_SINK@ -5%'
            echo 'bindsym --locked XF86AudioRaiseVolume  exec pactl set-sink-volume @DEFAULT_SINK@ +5%'
            echo 'bindsym --locked XF86AudioMicMute      exec pactl set-source-mute @DEFAULT_SOURCE@ toggle'
        fi

        if has playerctl; then
            echo 'bindsym --locked XF86AudioPlay  exec playerctl play-pause'
            echo 'bindsym --locked XF86AudioStop  exec playerctl stop'
            echo 'bindsym --locked XF86AudioPrev  exec playerctl previous'
            echo 'bindsym --locked XF86AudioNext  exec playerctl next'
        fi

        if has brightnessctl; then
            echo 'bindsym --locked XF86MonBrightnessUp   exec brightnessctl set +5%'
            echo 'bindsym --locked XF86MonBrightnessDown exec brightnessctl set 5%-'
        fi

        if has swaybg && [ -x "$HOME/.local/libexec/set-wallpaper" ]; then
            echo 'bindsym $mod+Ctrl+w exec sh -c "cm-image -m cover | ~/.local/libexec/set-wallpaper"'
        fi

        if has cm-volmixer; then
            echo 'bindsym $mod+BackSpace exec cm-volmixer'
        fi

        if has cm-alias; then
            echo 'bindsym $mod+a exec cm-alias'
        fi

        if has cm-media; then
            echo 'bindsym $mod+m exec cm-media'
        fi

        if has cm-network; then
            echo 'bindsym $mod+n exec cm-network'
        fi

        if has cm-bluetooth; then
            echo 'bindsym $mod+b exec cm-bluetooth'
        fi

        if has cm-swirl; then
            echo 'bindsym $mod+s exec cm-swirl pull'
            echo 'bindsym $mod+r exec cm-swirl swap'
            echo 'bindsym $mod+g exec cm-swirl focus'
        fi

    } > "$HOME/.config/sway/local/utilities.g"
    echo "  Generated ~/.config/sway/local/utilities.g"

    if ! [ -f "$HOME/.config/sway/local/custom.g" ]; then
        cat > "$HOME/.config/sway/local/custom.g" <<'EOF'
# Machine-specific overrides — add your own below
seat seat0 xcursor_theme Graphite-dark-mocha 24
EOF
        echo "  Created ~/.config/sway/local/custom.g"
    fi

    WALL=$(cat "$HOME/.config/wallpaper" 2>/dev/null) || true
    if [ -n "$WALL" ] && [ -f "$WALL" ]; then
        printf 'output * bg "%s" fill\n' "$WALL" > "$HOME/.config/sway/local/wallpaper.g"
        echo "  Generated ~/.config/sway/local/wallpaper.g"
    fi
else
    echo ""
    echo "  Clone and build patched sway:"
    echo "    (github.com/ — VFX/animations fork)"
    echo ""
    echo "    Build dependencies (Arch):"
    echo "      sudo pacman -S --needed meson ninja wayland wayland-protocols \\"
    echo "        pkg-config pcre2 json-c pango cairo gdk-pixbuf libevdev \\"
    echo "        libdrm libxkbcommon libinput pixman libpng libjpeg-turbo \\"
    echo "        fontconfig libxcb xcb-util-wm xcb-util-image libdisplay-info \\"
    echo "        hwdata libliftoff"
    echo ""
    echo "    Build dependencies (Void musl):"
    echo "      sudo xbps-install -S meson ninja pkg-config wayland-devel \\"
    echo "        wayland-protocols pcre2-devel json-c-devel pango-devel \\"
    echo "        cairo-devel gdk-pixbuf-devel libevdev-devel libdrm-devel \\"
    echo "        libxkbcommon-devel libinput-devel pixman-devel libpng-devel \\"
    echo "        libjpeg-turbo-devel fontconfig-devel libxcb-devel \\"
    echo "        xcb-util-wm-devel xcb-util-image-devel libdisplay-info-devel \\"
    echo "        libliftoff-devel hwdata"
    echo ""
    echo "    git clone git@github.com:username/sway.git ~/sway-patched"
    echo "    cd ~/sway-patched"
    echo "    meson setup build \\"
    echo "      -Db_lto=true \\"
    echo "      --buildtype=release \\"
    echo "      --default-library=static \\"
    echo "      -Dzsh-completions=false \\"
    echo "      -Dfish-completions=false \\"
    echo "      -Ddefault-wallpaper=false \\"
    echo "      -Dman-pages=disabled \\"
    echo "      -Dswaybar=false \\"
    echo "      -Dtray=disabled"
    echo "    ninja -C build"
    echo "    sudo ninja -C build install"
    echo ""
    echo "  Add to ~/.profile to auto-launch on TTY1:"
    echo '    if [ -z "$WAYLAND_DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then'
    echo '      exec sway'
    echo '    fi'
    echo ""
    echo "  On Void Linux, launch via:"
    echo "    dbus-run-session sway"
    echo ""
fi
