if ! has niri; then
    echo "  Skipping (niri not found)"
    return
fi

mkdir -p "$HOME/.config/niri/local"

if [ "$MOD_CHOICE" = "2" ]; then
    cat > "$HOME/.config/niri/local/mod.kdl" <<'EOF'
input {
    mod-key "Super"
    mod-key-nested "Alt"
}
EOF
else
    cat > "$HOME/.config/niri/local/mod.kdl" <<'EOF'
input {
    mod-key "Alt"
    mod-key-nested "Super"
}
EOF
fi
echo "  Generated ~/.config/niri/local/mod.kdl"

if ! [ -f "$HOME/.config/niri/local/outputs.kdl" ]; then
    cat > "$HOME/.config/niri/local/outputs.kdl" <<'EOF'
// Machine-specific output configuration
// Find output names: niri msg outputs
//
// Example: output "Virtual-1" {
//     mode custom=true "3440x1440@60"
//     scale 1.25
// }
EOF
    echo "  Created ~/.config/niri/local/outputs.kdl"
fi

{
    echo "// Auto-generated by bootstrap — reflects currently installed packages"
    echo "// Do not edit manually; use local/custom.kdl instead"
    echo ""

    if has waybar; then
        echo 'spawn-at-startup "waybar"'
    fi

    if has swayidle && has powerctl; then
        echo 'spawn-at-startup "swayidle" "-w" "timeout" "300" "powerctl lock" "timeout" "600" "niri msg action power-off-monitors" "resume" "niri msg action power-on-monitors" "before-sleep" "powerctl lock"'
    fi

    echo ""
    echo "binds {"

    if has "$TERMINAL"; then
        echo "    Mod+Return hotkey-overlay-title=\"Open a Terminal\" { spawn \"$TERMINAL\"; }"
    fi

    if has rofi; then
        echo '    Mod+D hotkey-overlay-title="Run an Application" { spawn "rofi -dmenu"; }'
    fi

    if has powerctl; then
        echo '    Super+Alt+L hotkey-overlay-title="Lock the Screen" { spawn "powerctl lock"; }'
    fi

    if has pactl; then
        echo '    XF86AudioRaiseVolume allow-when-locked=true { spawn-sh "pactl set-sink-volume @DEFAULT_SINK@ +1%"; }'
        echo '    XF86AudioLowerVolume allow-when-locked=true { spawn-sh "pactl set-sink-volume @DEFAULT_SINK@ -1%"; }'
        echo '    XF86AudioMute        allow-when-locked=true { spawn-sh "pactl set-sink-mute @DEFAULT_SINK@ toggle"; }'
        echo '    XF86AudioMicMute     allow-when-locked=true { spawn-sh "pactl set-source-mute @DEFAULT_SOURCE@ toggle"; }'
    fi

    if has playerctl; then
        echo '    XF86AudioPlay allow-when-locked=true { spawn-sh "playerctl play-pause"; }'
        echo '    XF86AudioStop allow-when-locked=true { spawn-sh "playerctl stop"; }'
        echo '    XF86AudioPrev allow-when-locked=true { spawn-sh "playerctl previous"; }'
        echo '    XF86AudioNext allow-when-locked=true { spawn-sh "playerctl next"; }'
    fi

    if has brightnessctl; then
        echo '    XF86MonBrightnessUp   allow-when-locked=true { spawn "brightnessctl" "--class=backlight" "set" "+10%"; }'
        echo '    XF86MonBrightnessDown allow-when-locked=true { spawn "brightnessctl" "--class=backlight" "set" "10%-"; }'
    fi

    if has orca; then
        echo '    Super+Alt+S allow-when-locked=true hotkey-overlay-title=null { spawn-sh "pkill orca || exec orca"; }'
    fi

    if has rofi; then
        echo '    Mod+Ctrl+W hotkey-overlay-title="Change Wallpaper" { spawn "rofi-wallpaper"; }'
    fi

    if has rofi-volmixer; then
        echo '    Mod+BackSpace hotkey-overlay-title="Volume Mixer" { spawn "rofi-volmixer"; }'
    fi

    echo "}"
} > "$HOME/.config/niri/local/autostart.kdl"
echo "  Generated ~/.config/niri/local/autostart.kdl"

if ! [ -f "$HOME/.config/niri/local/custom.kdl" ]; then
    cat > "$HOME/.config/niri/local/custom.kdl" <<'EOF'
// Machine-specific overrides — add your own below
EOF
    echo "  Created ~/.config/niri/local/custom.kdl"
fi

mkdir -p "$HOME/.config/niri/local"
WALL=$(cat "$HOME/.config/wallpaper" 2>/dev/null)
if [ -n "$WALL" ] && [ -f "$WALL" ]; then
    printf 'spawn-at-startup "swaybg" "-i" "%s" "-m" "fill"\n' "$WALL" > "$HOME/.config/niri/local/wallpaper.kdl"
    echo "  Generated ~/.config/niri/local/wallpaper.kdl"
fi

echo "Linking niri config..."
link "$DOTFILES/niri/config.kdl" "$HOME/.config/niri/config.kdl"
