background = "#1e1e2ee6"
prompt_text = "#b4befe"
selection_bg = "#f5c2e799"
selection_text = "#1e1e2e"
input_bg = "#31324499"
input_text = "#cdd6f4"
item_text = "#cdd6f4"
item_dim_text = "#6c7080"
cursor_color = "#f5c2e7"
border = "#45475a99"
border_width = 3
border_radius = 20
input_radius = 10
input_border_width = 2
selection_border_width = 2
selection_radius = 10
list_border_width = 0
list_border_radius = 0
margin = 14
input_pad = 6
item_pad = 24
item_spacing = 4
shadow_blur_sigma = 5.0
font_size = 12
font_family = "afio"
width = 1080
lines = 5
thumb_width = 120
