#!/usr/bin/env bash
# Dotfiles bootstrap — Linux
set -euo pipefail

DOTFILES="$(cd "$(dirname "$0")" && pwd)"

missing=()
for cmd in starship nvim kanata rofi foot pactl sway swaylock waybar swayidle; do
    command -v "$cmd" &>/dev/null || missing+=("$cmd")
done
if ! command -v unzip &>/dev/null; then
    missing+=("unzip")
fi

if [[ ${#missing[@]} -gt 0 ]]; then
    echo "Not found: ${missing[*]}"
    echo "Configs for missing tools will be skipped."
    read -rp "Continue? [y/N] " ans
    [[ "$ans" =~ ^[yY] ]] || exit 1
fi

echo ""
echo "Sway \$mod key:"
echo "  1) Alt (Mod1)"
echo "  2) Win/Super (Mod4)"
read -rp "Pick [1/2]: " mod_choice
if [ "$mod_choice" = "2" ]; then
    sed -i 's/set \$mod Mod1/set \$mod Mod4/' "$DOTFILES/sway/config"
    sed -i 's/Alt+BackSpace/Super+BackSpace/' "$DOTFILES/local/bin/wallpaper-picker"
fi

has() { command -v "$1" &>/dev/null; }

link() {
    local src="$1" dst="$2"
    [[ ! -e "$src" ]] && { echo "  Skipping (src missing): $src"; return; }
    if [[ -L "$dst" && "$(readlink "$dst")" == "$src" ]]; then
        echo "  OK"
        return
    fi
    rm -rf "$dst"
    mkdir -p "$(dirname "$dst")"
    ln -sf "$src" "$dst"
    echo "  Linked: $dst → $src"
}

if has starship; then
    echo "Linking starship.toml..."
    link "$DOTFILES/starship.toml" "$HOME/.config/starship.toml"
fi

if has nvim; then
    echo "Linking nvim config..."
    link "$DOTFILES/nvim" "$HOME/.config/nvim"
fi

if has foot && [ -d "$DOTFILES/foot" ]; then
    echo "Linking foot config..."
    link "$DOTFILES/foot/foot.ini" "$HOME/.config/foot/foot.ini"
fi

if [ -f "$DOTFILES/fonts/IosevkaCustom.zip" ]; then
    echo "Installing Iosevka Custom font..."
    FONT_DIR="$HOME/.local/share/fonts/iosevka-custom"
    mkdir -p "$FONT_DIR"
    unzip -jo "$DOTFILES/fonts/IosevkaCustom.zip" -d "$FONT_DIR"
    cp "$DOTFILES/fonts/LICENSE.md" "$FONT_DIR/"
    fc-cache -fv "$FONT_DIR" &>/dev/null
    echo "  Font installed"
fi

if has kanata; then
    echo "Linking kanata config..."
    link "$DOTFILES/kanata/kanata.kbd" "$HOME/.config/kanata/kanata.kbd"

    if has systemctl; then
        echo "Linking kanata systemd service..."
        link "$DOTFILES/kanata/kanata.service" "$HOME/.config/systemd/user/kanata.service"
        systemctl --user daemon-reload || true
        if ! systemctl --user is-enabled kanata.service &>/dev/null; then
            systemctl --user enable --now kanata.service
            echo "  kanata service enabled and started"
        else
            echo "  kanata service already enabled"
        fi
    fi
fi

if has rofi; then
    echo "Linking rofi config..."
    link "$DOTFILES/rofi/config.rasi" "$HOME/.config/rofi/config.rasi"
    link "$DOTFILES/rofi/themes/catppuccin-mocha.rasi" "$HOME/.config/rofi/themes/catppuccin-mocha.rasi"
fi

# --- wallpapers symlink (before sway so wallpaper file gets correct path) ---
if [ -d "$DOTFILES/wallpapers" ]; then
    if [ -L "$HOME/Pictures/wallpapers" ]; then
        echo "  ~/Pictures/wallpapers already a symlink — skipping"
    elif [ -d "$HOME/Pictures/wallpapers" ]; then
        echo "  Copying existing wallpapers into submodule..."
        cp -r "$HOME/Pictures/wallpapers/"* "$DOTFILES/wallpapers/"
        rm -rf "$HOME/Pictures/wallpapers"
        ln -sf "$DOTFILES/wallpapers" "$HOME/Pictures/wallpapers"
        echo "  Copied and symlinked"
    else
        mkdir -p "$HOME/Pictures"
        ln -sf "$DOTFILES/wallpapers" "$HOME/Pictures/wallpapers"
        echo "  Linked: ~/Pictures/wallpapers → dotfiles/wallpapers"
    fi
fi

# --- sway ---
if has sway; then
    echo "Linking sway config..."
    link "$DOTFILES/sway/config" "$HOME/.config/sway/config"

    mkdir -p "$HOME/.config/sway/local"

    if ! [ -f "$HOME/.config/sway/local/outputs" ]; then
        {
            echo "# Machine-specific output configuration"
            echo "# e.g. output eDP-1 resolution 1920x1080@60Hz position 0,0"
        } > "$HOME/.config/sway/local/outputs"
        echo "  Created ~/.config/sway/local/outputs"
    fi

    if ! [ -f "$HOME/.config/sway/local/wallpaper" ]; then
        WALL="$HOME/Pictures/wallpapers/Catppuccin Mocha/01. Catppuccin Mocha.png"
        if [ -f "$WALL" ]; then
            echo "output * bg \"$WALL\" fill" > "$HOME/.config/sway/local/wallpaper"
            echo "  Created ~/.config/sway/local/wallpaper"
        else
            {
                echo "# Edit this path to set your wallpaper"
                echo "# e.g. output * bg \"$HOME/Pictures/wallpapers/...\" fill"
            } > "$HOME/.config/sway/local/wallpaper"
            echo "  Created ~/.config/sway/local/wallpaper"
        fi
    fi

    {
        echo "# Auto-generated by bootstrap — reflects currently installed packages"
        echo "# Do not edit manually; use local/custom instead"
        echo ""

        if has rofi; then
            echo "bindsym \$mod+Shift+w exec ~/.local/bin/wallpaper-picker"
        fi

        if has pactl; then
            echo "bindsym --locked XF86AudioMute exec pactl set-sink-mute @DEFAULT_SINK@ toggle"
            echo "bindsym --locked XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -5%"
            echo "bindsym --locked XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +5%"
            echo "bindsym --locked XF86AudioMicMute exec pactl set-source-mute @DEFAULT_SOURCE@ toggle"
            echo "bindsym \$mod+m exec pactl set-source-mute @DEFAULT_SOURCE@ toggle"

            echo "bindsym \$mod+Shift+m exec ~/.local/bin/volmixer"
        fi
    } > "$HOME/.config/sway/local/utilities.g"
    echo "  Generated ~/.config/sway/local/utilities.g"

    if ! [ -f "$HOME/.config/sway/local/custom" ]; then
        {
            echo "# Machine-specific custom keybinds -- add your own below"
            echo "# e.g. bindsym --locked XF86MonBrightnessUp exec brightnessctl set +10%"
            echo ""
            echo "seat seat0 xcursor_theme Adwaita 24"
        } > "$HOME/.config/sway/local/custom"
        echo "  Created ~/.config/sway/local/custom"
    fi
fi

if has swaylock; then
    echo "Linking swaylock config..."
    link "$DOTFILES/swaylock/config" "$HOME/.config/swaylock/config"
fi

if has waybar; then
    echo "Linking waybar config..."
    link "$DOTFILES/waybar/config.jsonc" "$HOME/.config/waybar/config.jsonc"
    link "$DOTFILES/waybar/style.css" "$HOME/.config/waybar/style.css"
fi

# --- wallpaper-picker (needs both sway and rofi) ---
if has sway && has rofi; then
    if [ -f "$DOTFILES/local/bin/wallpaper-picker" ]; then
        echo "Linking wallpaper-picker..."
        link "$DOTFILES/local/bin/wallpaper-picker" "$HOME/.local/bin/wallpaper-picker"
    fi
    link "$DOTFILES/rofi/themes/wallpaper.rasi" "$HOME/.config/rofi/themes/wallpaper.rasi"
fi

if has rofi; then
    echo "Installing openwith script and config..."
    link "$DOTFILES/openwith/openwith" "$HOME/.local/bin/openwith"
    link "$DOTFILES/openwith/config" "$HOME/.config/openwith/config"

    if has pactl; then
        link "$DOTFILES/openwith/volmixer" "$HOME/.local/bin/volmixer"
    fi

    echo "Installing openwith desktop entry..."
    link "$DOTFILES/local/share/applications/openwith.desktop" "$HOME/.local/share/applications/openwith.desktop"

    echo "Registering openwith as default for all MIME types..."
    {
        echo "[Default Applications]"
        find /usr/share/mime -mindepth 2 -maxdepth 2 -name '*.xml' \
          -not -path '*/packages/*' \
        | sed 's|.*/mime/||; s|\.xml$||' \
        | sort -u \
        | awk '{printf "%s=openwith.desktop\n", $0}'
        echo "inode/x-empty=openwith.desktop"
    } > "$HOME/.config/mimeapps.list"
    echo "  Registered $(wc -l < "$HOME/.config/mimeapps.list") MIME types"
fi

echo "Done! Open Neovim to install plugins."
