--[[
Reference: Original Dracula token color overrides
Removed when switching to Catppuccin Mocha.
If you want to restore these, replace the corresponding
Catppuccin sections in init.lua with these values.

  -- Official Dracula token colors for all languages
  vim.api.nvim_set_hl(0, '@comment', { fg = '#6272A4' })
  vim.api.nvim_set_hl(0, '@keyword', { fg = '#FF79C6' })
  vim.api.nvim_set_hl(0, '@conditional', { link = '@keyword' })
  vim.api.nvim_set_hl(0, '@repeat', { link = '@keyword' })
  vim.api.nvim_set_hl(0, '@include', { link = '@keyword' })
  vim.api.nvim_set_hl(0, '@exception', { link = '@keyword' })
  vim.api.nvim_set_hl(0, '@keyword.storage', { link = '@keyword' })
  vim.api.nvim_set_hl(0, '@keyword.modifier', { link = '@keyword' })
  vim.api.nvim_set_hl(0, '@keyword.control', { link = '@keyword' })
  vim.api.nvim_set_hl(0, '@lsp.type.keyword', { link = '@keyword' })
  vim.api.nvim_set_hl(0, '@operator', { fg = '#F8F8F2' })
  vim.api.nvim_set_hl(0, '@function', { fg = '#50FA7B' })
  vim.api.nvim_set_hl(0, '@function.builtin', { fg = '#8BE9FD' })
  vim.api.nvim_set_hl(0, '@lsp.type.function', { link = '@function' })
  vim.api.nvim_set_hl(0, '@lsp.type.method', { link = '@function' })
  vim.api.nvim_set_hl(0, '@lsp.type.property', { link = '@property' })
  vim.api.nvim_set_hl(0, '@method', { link = '@function' })
  vim.api.nvim_set_hl(0, '@constructor', { link = '@function' })
  vim.api.nvim_set_hl(0, '@type', { fg = '#8BE9FD' })
  vim.api.nvim_set_hl(0, '@type.builtin', { link = '@type' })
  vim.api.nvim_set_hl(0, '@type.definition', { link = '@type' })
  vim.api.nvim_set_hl(0, '@string', { fg = '#F1FA8C' })
  vim.api.nvim_set_hl(0, '@string.regexp', { link = '@string' })
  vim.api.nvim_set_hl(0, '@string.escape', { fg = '#FF79C6' })
  vim.api.nvim_set_hl(0, '@constant', { fg = '#BD93F9' })
  vim.api.nvim_set_hl(0, '@number', { link = '@constant' })
  vim.api.nvim_set_hl(0, '@boolean', { link = '@constant' })
  vim.api.nvim_set_hl(0, '@character', { link = '@constant' })
  vim.api.nvim_set_hl(0, '@lsp.type.constant', { link = '@constant' })
  vim.api.nvim_set_hl(0, '@lsp.type.constantName', { link = '@constant' })
  vim.api.nvim_set_hl(0, '@lsp.type.namespace', { fg = '#C79DD6' })
  vim.api.nvim_set_hl(0, '@lsp.type.typeParameter', { fg = '#FFB86C' })
  vim.api.nvim_set_hl(0, '@lsp.type.delegateName', { link = '@type' })
  vim.api.nvim_set_hl(0, '@lsp.type.fieldName', { link = '@property' })
  vim.api.nvim_set_hl(0, '@lsp.type.variable', { link = '@variable' })
  vim.api.nvim_set_hl(0, '@lsp.type.parameter', { link = '@variable.parameter' })
  vim.api.nvim_set_hl(0, '@variable', { fg = '#F8F8F2' })
  vim.api.nvim_set_hl(0, '@variable.parameter', { fg = '#FFB86C' })
  vim.api.nvim_set_hl(0, '@property', { fg = '#F8F8F2' })
  vim.api.nvim_set_hl(0, '@variable.member', { link = '@property' })
  vim.api.nvim_set_hl(0, '@variable.global', { link = '@property' })
  vim.api.nvim_set_hl(0, '@tag', { fg = '#FF79C6' })
  vim.api.nvim_set_hl(0, '@tag.attribute', { fg = '#50FA7B' })
  vim.api.nvim_set_hl(0, '@tag.delimiter', { fg = '#F8F8F2' })
  vim.api.nvim_set_hl(0, '@error', { fg = '#FF5555' })
  vim.api.nvim_set_hl(0, '@markup.heading', { fg = '#BD93F9' })
  vim.api.nvim_set_hl(0, '@markup.bold', { fg = '#FFB86C' })
  vim.api.nvim_set_hl(0, '@markup.italic', { fg = '#F1FA8C' })
  vim.api.nvim_set_hl(0, '@diff.plus', { fg = '#50FA7B' })
  vim.api.nvim_set_hl(0, '@diff.minus', { fg = '#FF5555' })

  -- LSP reference highlights (background block like VSCode)
  vim.api.nvim_set_hl(0, 'LspReferenceText', { bg = '#44475A' })
  vim.api.nvim_set_hl(0, 'LspReferenceRead', { bg = '#44475A' })
  vim.api.nvim_set_hl(0, 'LspReferenceWrite', { bg = '#44475A' })

  -- C# semantic token colors (matching VSCode Dracula theme)
  vim.api.nvim_create_autocmd('LspAttach', {
    group = vim.api.nvim_create_augroup('csharp-colors', { clear = true }),
    callback = function(ev)
      if vim.bo[ev.buf].filetype ~= 'cs' then return end
      vim.api.nvim_set_hl(0, '@lsp.type.class', { fg = '#909df8' })
      vim.api.nvim_set_hl(0, '@lsp.type.struct', { fg = '#78c5f2' })
      vim.api.nvim_set_hl(0, '@lsp.type.interface', { fg = '#78f2a5' })
      vim.api.nvim_set_hl(0, '@lsp.type.enum', { fg = '#f2e278' })
      vim.api.nvim_set_hl(0, '@lsp.type.enumMember', { fg = '#f4d17b' })
      vim.api.nvim_set_hl(0, '@lsp.type.event', { fg = '#FFB86C' })
      vim.api.nvim_set_hl(0, '@lsp.type.field', { fg = '#FFB86C' })
      vim.api.nvim_set_hl(0, '@lsp.type.fieldName', { fg = '#FFB86C' })
      vim.api.nvim_set_hl(0, '@lsp.type.namespace', { fg = '#6272A4' })
      vim.api.nvim_set_hl(0, '@lsp.type.delegateName', { fg = '#79B84A' })
      vim.api.nvim_set_hl(0, '@variable', { fg = '#ededed' })
      vim.api.nvim_set_hl(0, '@variable.parameter', { fg = '#c5f278' })
      vim.api.nvim_set_hl(0, '@variable.member', { fg = '#FFB86C' })
      vim.api.nvim_set_hl(0, '@property', { fg = '#FFB86C' })
      vim.api.nvim_set_hl(0, '@variable.global', { fg = '#FFB86C' })
    end,
  })
]]
